mysql-account: 2023221547
spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/${mysql-account}?createDatabaseIfNotExist=true'
    username: ${mysql-account}
    password: ${mysql-account}
  sql:
    init:
      mode: always

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    sql: debug
    org.example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

my:
  secretkey: Qye35Fd