mysql-account: 2023221547
spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/${mysql-account}?createDatabaseIfNotExist=true'
    username: ${mysql-account}
    password: ${mysql-account}
  sql:
    init:
      mode: always

  jackson:
    default-property-inclusion: non_null
